---
# setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  static: no

- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  static: no

# web interface service
- name: Ensure OMSA services are started and enabled to start at boot.
  service: name=dsm_om_connsvc state=started enabled=yes
  with_items:
    - instsvcdrv
    - dsm_sa_ipmi
    - mptctl
    - dsm_om_connsvc
    - dsm_om_shrsvc
    - dataeng
