---
# setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  static: no

- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  static: no

# web interface service
- name: Ensure OMSA web interface is started and enabled to start at boot.
  service: name=dsm_om_connsvc state=started enabled=yes
