# ---
# # setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  static: no

- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  static: no

# web interface service
- name: Ensure OMSA services are started and enabled to start at boot.
  service: name={{ item }} state=started enabled=yes
  with_items:
    - instsvcdrv
    - dsm_om_connsvc
    - dataeng
